version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "jest"
      - dependency-name: "@squoosh/lib"

  - package-ecosystem: "npm"
    directory: "/example/cjs"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "del"

  - package-ecosystem: "npm"
    directory: "/example/esm"
    schedule:
      interval: "weekly"
